name: Deploy Web

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Validar botón del pipeline
        run: |
          grep "Ver Pipeline" index.html

  build:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Subir sitio como artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Desplegar sitio
        uses: actions/deploy-pages@v4