name: Pipeline con Error

on:
  push:

jobs:
  probar-error:
    runs-on: ubuntu-latest

    steps:
      - name: Paso 1 - Mensaje inicial
        run: echo "Iniciando pipeline"

      - name: Paso 2 - Comando corregido
        run: echo "Ahora el pipeline funciona"

      - name: Paso 3 - Este paso no debería ejecutarse
        run: echo "Si ves esto, pasasteee"