name: Pipeline Optimizado

on:
  push:

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Crear archivo de resultado
        run: echo "Pipeline exitoso" > resultado.txt

      - name: Guardar artefacto
        uses: actions/upload-artifact@v4
        with:
          name: resultado-pipeline
          path: resultado.txt

  despliegue:
    needs: validar
    runs-on: ubuntu-latest

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: resultado-pipeline

      - name: Leer archivo
        run: cat resultado.txt

      - name: Simular despliegue
        run: echo "Desplegando aplicación..."